var tvnews = [
  {
    "title": "Fox",
    "url": "https://www.foxnews.com/",
    "type": "red-tv",
    "lean": "",
    "launchYear": "",
    "logo": "",
    "scale": "",
    "country": "United States",
    "state": "",
    "genre": "",
    "info": ""
  },
  {
    "title": "CNN",
    "url": "https://www.cnn.com/",
    "type": "grey-tv",
    "lean": "",
    "launchYear": "",
    "logo": "",
    "scale": "",
    "country": "United States",
    "state": "",
    "genre": "",
    "info": ""
  },
  {
    "title": "MSNBC",
    "url": "https://www.msnbc.com/",
    "type": "blue-tv",
    "lean": "",
    "launchYear": "",
    "logo": "",
    "scale": "",
    "country": "United States",
    "state": "",
    "genre": "",
    "info": ""
  },
  {
    "title": "ABC",
    "url": "https://abcnews.go.com/",
    "type": "grey-tv",
    "lean": "",
    "launchYear": "",
    "logo": "",
    "scale": "",
    "country": "United States",
    "state": "",
    "genre": "",
    "info": ""
  },
  {
    "title": "CBS",
    "url": "https://www.cbsnews.com/",
    "type": "grey-tv",
    "lean": "",
    "launchYear": "",
    "logo": "",
    "scale": "",
    "country": "United States",
    "state": "",
    "genre": "",
    "info": ""
  },
  {
    "title": "NBC",
    "url": "https://www.nbcnews.com/",
    "type": "blue-tv",
    "lean": "",
    "launchYear": "",
    "logo": "",
    "scale": "",
    "country": "United States",
    "state": "",
    "genre": "",
    "info": ""
  },
  {
    "title": "News Max",
    "url": "https://www.newsmax.com/",
    "type": "red-tv",
    "lean": "",
    "launchYear": "",
    "logo": "",
    "scale": "",
    "country": "United States",
    "state": "",
    "genre": "",
    "info": ""
  },
  {
    "title": "NPR",
    "url": "https://www.npr.org/",
    "type": "blue-tv",
    "lean": "",
    "launchYear": "",
    "logo": "",
    "scale": "",
    "country": "United States",
    "state": "",
    "genre": "",
    "info": ""
  },
  {
    "title": "PBS",
    "url": "https://www.pbs.org/newshour/",
    "type": "grey-tv",
    "lean": "",
    "launchYear": "",
    "logo": "",
    "scale": "",
    "country": "United States",
    "state": "",
    "genre": "",
    "info": ""
  },
  {
    "title": "CNBC",
    "url": "https://www.cnbc.com/",
    "type": "grey-tv",
    "lean": "",
    "launchYear": "",
    "logo": "",
    "scale": "",
    "country": "United States",
    "state": "",
    "genre": "",
    "info": ""
  },
  {
    "title": "VOA",
    "url": "https://www.oann.com/",
    "type": "grey-tv",
    "lean": "",
    "launchYear": "",
    "logo": "",
    "scale": "",
    "country": "United States",
    "state": "",
    "genre": "",
    "info": ""
  },
  {
    "title": "Voice of America",
    "url": "https://www.voanews.com/",
    "type": "grey-tv",
    "lean": "",
    "launchYear": "",
    "logo": "",
    "scale": "",
    "country": "United States",
    "state": "",
    "genre": "",
    "info": ""
  }
];
